#core/config.py
import os

SECRET_KEY = os.getenv("SECRET_KEY", "INSERT SECRET KEY HERE")
APP_ENV= os.getenv("APP_ENV", "dev")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 15
REFRESH_TOKEN_EXPIRE_DAYS = 7